# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: React GPT Forked Package

on:
  push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure the node version used on GitHub-hosted runners
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: '@dennisinteractive'
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Start chrome
        run: |
          export CHROME_BIN=chromium-browser
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Install dependencies
        run: yarn install
      - name: Run Tests
        env:
          CHROME_BIN: 'chromium-browser'
          DISPLAY: ':99.0'
        run: yarn test
      - name: Build Test Package
        if: contains(github.ref, 'test')
        run: yarn build:umd
      - name: Build Production
        if: "!contains(github.ref, 'test')"
        run: yarn build:umd:min
      - name: Publish to Github Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: yarn publish